# Generated by Django 3.2.12 on 2022-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_remove_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Image',
            field=models.ImageField(default=2, upload_to='IMG'),
            preserve_default=False,
        ),
    ]
