# Generated by Django 3.2.12 on 2022-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Publish_year',
            field=models.IntegerField(default=1993),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.TextField(max_length=70),
        ),
    ]
