# Generated by Django 3.2.12 on 2022-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_auto_20220225_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.CharField(max_length=70),
        ),
    ]
