# Generated by Django 3.2.12 on 2022-03-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_alter_books_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Writer',
            field=models.CharField(default='ff', max_length=70),
            preserve_default=False,
        ),
    ]
